### ISSUE TITLE
Auto-detect language

### ISSUE THREAD

**Issue by krzysztofmajewski** [untra/polyglot#121]
I'm using polyglot for a bilingual (French and English) site. Currently the default_lang is en. I would like the site to auto-detect the user's preferred language, probably via the `Accept-Language` header. Discussion in [this Issue](https://github.com/untra/polyglot/issues/60) suggests that this can be achieved via webserver configuration, by redirecting to the appropriate localized version of the deployed site based on inspecting the header. I'm open to that. However, there is currently no convenient/elegant path for me to do this. That's because I'm running the `nginx` webserver, and the [relevant module](https://www.nginx.com/resources/wiki/modules/accept_language/) requires me to recompile `nginx`. I can do that, but it would imply missing out on `nginx` updates from the distribution vendor (Ubuntu in my case). 

Opening a new issue as suggested by @untra .

**Comment by Roman1001** [comment]
Good idea. But I don’t think you have to struggle with webserver configuration, as it can be done with JavaScript [like here](https://stackoverflow.com/questions/8199760/how-to-get-the-browser-language-using-javascript). Then we can just make a JS file redirecting us to the right language.

Something like this:
```js
var browserlang = navigator.language || navigator.userLanguage;
if (browserlang.includes('en')) { window.location = '/en/'; }
if (browserlang.includes('fr')) { window.location = '/fr/'; }
```

Of course, you’ll have to execute this code ONLY on the site’s `index.html` — otherwise the user will keep being redirected to the homepage.
To avoid this, you could also let this script display a banner at the top of the page saying there’s a page in the user’s language (then execute on all pages).

There’s one disadvantage: the JS code will be executed in the user’s browser. When the user has disabled JavaScript execution, this script doesn’t work.

**Comment by victorbnl** [comment]
If we put this code on the default language's index to be on `/`, i.e. the english index, the user who wants the english index will fall in a redirect loop

**Comment by garraflavatra** [comment]
@victorbnl You’re right, otherwise you can make a friendly dialog, e.g. as Apple does:

![A49DBBB6-4F47-46F4-AE49-1503ADCA339E](https://user-images.githubusercontent.com/34036573/118152984-a924b480-b415-11eb-8254-31d3357344d1.jpeg)

**Comment by victorbnl** [comment]
I'd say that's absolutely not a solution, that's an awful user-experience, the goal would be to just display directly the correct page to the user
