### ISSUE TITLE
exclude from localization not working , using '*.gem'  makes polyglot crash

### ISSUE THREAD

**Issue by pavanjoshi914** [untra/polyglot#132]
I am using jekyll 3.9.0  I am facing majorly 2 problems 
1>assests are still being copied to localized folder
 I have assets folder in root directory of my project
 ```exclude_from_localization: ["assets"] ```
![assets](https://user-images.githubusercontent.com/55848322/112611018-51b98d80-8e43-11eb-93f8-0aa5569d3021.png)
 adding entries "*.gemspec" and "*.gem" generates relative regex errors
![exclude from localization](https://user-images.githubusercontent.com/55848322/112611031-54b47e00-8e43-11eb-93f1-1d75832dcade.png)
![2021-03-26_15-04](https://user-images.githubusercontent.com/55848322/112612134-95f95d80-8e44-11eb-850c-2c56482f5cb3.png)
I want to know is there any fix for such issues

**Comment by untra** [comment]
Heya @pavanjoshi914 the `exclude_from_localization` array takes in a list of strings that are file/folder paths from the root directory where you run jekyll serve. It does not support glob matching on filenames. `*-` wont work. sorry!

re: your assets directory still being created, [are you using the minima gem](https://github.com/untra/polyglot/issues/130#issuecomment-782754522)?

For further help and debugging, send me a link to your repo and I'll clone it down and take a look.

**Comment by pavanjoshi914** [comment]
Thanks for quick reply @untra 
https://github.com/pavanjoshi914/Interactive-Book here is the link for repo please checkout on ```GSoD2020``` branch to see newer version of site 
site is using  [just-the-docs](https://github.com/pmarsceill/just-the-docs) theme

**Comment by untra** [comment]
yeah, so... the `minima` gem, when added to the gemfile and run part of jekyll, checks if the icon and css files in the [assets](https://github.com/jekyll/minima#assets) directory are there, and if not it creates those files in the build output directory _after the site is built._ Minima does this in the post-build step of the jekyll run process, which is after polyglot executes and splits in execution and each language has a different build folder output.

polyglot can't prevent this from happening, because it's part of the hook execution of a completely different jekyll plugin. `minima`'s "batteries included" conflict with polyglot's here.

You have two workarounds here:
* create those files exactly as they are now in the site build output directory, and just be cool with those extra files hanging around not being recreated
* just don't use the minima gem with your project

also: I don't see `jekyll-polyglot` listed in your gemfile on that branch, and I think [the section of config you referenced](https://github.com/pavanjoshi914/Interactive-Book/blob/GSoD2020/_config.yml#L63) is for jekyll sites `exclude:` [configuration](https://jekyllrb.com/docs/configuration/options/), which probably  also doesn't allow glob matching.

`exclude: []` specific files and directories you want in your build repo but not in the built site (eg. `node_modules, gemfile, readme, etc.`)
`exclude_from_localization: []` specific files you want in your built site, but not in your sublanguage sites (eg. `assets, images, css, etc.` directory)

Hopefully this helps. Let me know if you have further questions about polyglot.
