### ISSUE TITLE
the ferh mystery

### ISSUE THREAD

**Issue by elotroalex** [untra/polyglot#158]
hi @untra. Thanks for this wonderful gem. Just ran into a glitch that I hadn't before. This is my 3rd site using your gem. In this glitch for some reason this code generates a `ferh=` inside my `<a>` element, instead of the expected `href=`. Needless to say, the links in the language switcher don't work:

```
<!-- LANGUAGE SELECTION -->                 
                
           {% for language in site.languages %}
              {% if language == site.active_lang %}{% else %}
                <li><a style="color: #0080ff;" {% static_href %} href="{% if language == site.default_lang %}{{ "" | absolute_url}}{{page.url | remove: "/"}}{% else %}{{"" | absolute_url}}{{ language }}{{page.url}}{% endif %}"{% endstatic_href %} >
                {{ language }}</a></li>
              {%endif%}
          {% endfor %}
```

**Comment by elotroalex** [comment]
Interesting to note is that this only happens with `$ jekyll build` and not on `$ jekyll serve`. I'm kinda amazed by this glitch.

**Comment by elotroalex** [comment]
Ah. Just found that you write this explicitly wrong so that you can catch it with a post-processor:

```


# href writes out as ferh="..." explicitly wrong, to be cauaght by seperate processor for nonrelativized links
--


          <span class="pl-s">"<span class="text-bold hx_keyword-hl rounded-2 d-inline-block">ferh</span>=<span class="pl-s1"><span class="pl-kos">#{</span><span class="pl-s1">href_value</span><span class="pl-kos">}</span></span>"</span>```
          
This means the `static_href` might not be functioning fully somehow in my line.

**Comment by untra** [comment]
Hello @elotroalex 👋 , thanks for the praise, and sorry for the bug.

Yeah that is supposed to be caught by the postprocessor, which honestly is not a good approach and is rather wasteful.

> Interesting to note is that this only happens with `$ jekyll build` and not on `$ jekyll serve`. I'm kinda amazed by this glitch.

now that is curious; I wonder why the different jekyll build commands would do that? is the build process actually running polyglot and relativizing? If you shoot me a link to your project I'd be happy to look

**Comment by lucmartinon** [comment]
Hello, 
I would like to reopen this issue: I also have a project where I don't use `jekyll serve`, only `jekyll build`, since I have anyway an nginx server running to serve a data api. I seems to me that this is causing the `static_href` tag to not function. 

I added a detailled example on a personal website that is in construction: 

code here: 
https://gitlab.com/lucmartinon/cnrs_pfas_web/-/blob/main/frontend/pages/about.fr.md?ref_type=heads

which is published here
http://vps-8ea64a15.vps.ovh.net/fr/about/

the link to `/about` is changed to `/fr/about` although it is in a `static_href` tag. 

Beside this, fantastic plugin! thanks a lot!
