### ISSUE TITLE
No sense plugin.

### ISSUE THREAD

**Issue by equinusocio** [untra/polyglot#17]
I can not find a logical sense to write a page for each language, I might as well do it by hand. (And you have to do anyway even with the plugin).

It would make sense to create one file per page and have them completed for all set languages. Like:

```
/
_pages/ 
  |__ index.liquid
  |__ about.liquid
  |__ contacts.liquid

_data/
  |__ it/
  |__ |__ index.yml
  |__ |__ about.yml
  |__ |__ contacts.yml
  |
  |__ en/
  |__ |__ index.yml
  |__ |__ about.yml
  |__ |__ contacts.yml
```

So by this way i will write only a page template and use a plugin inside that grab each respective language file (for all set languages) during the compilation. **There is a way to use this structure and the plugins to generate the languages subfolder based on `.yml` data files?**

**Comment by untra** [comment]
@equinusocio Storing strings of each languages content in yaml files is a frequently used design pattern for multi-language software. It is also a design pattern that I recommend using in conjunction with this plugin for rich content such as navigation, banners, and short strings.

For very large strings (such as for entire pages of web content), this design pattern used exclusively is a bad idea. 
* It requires you to juggle key/values between your template and your language files. Doing this for a site-wide navbar is one thing, but for _every page_ on your website is a nightmare. 
* It does not provide fallback support to a default language, which means you must have key/value pairs ready made for every language you wish to support.
* Debugging and maintaining your pages will be harder, because the strings on the pages are scattered across yaml files. 

This comes from my own personal experience. Unless your website is small and your languages few, I do not recommend you use this design pattern exclusively. This approach only works well if you have all of the multi-language content ready, and are organized enough to keep track of _every string on your website_.

Are there other reasons why you don't like this approach?

**Comment by equinusocio** [comment]
@untra What i need is to write only one file per page (example about.html) and put inside the relative yml string that will be compiled for each languages. And return

```
index.html
about.html (ita default)
/en
|__ index.html
|__ about.html
```

there is a way to get this with this plugin?

**Comment by untra** [comment]
Yes, you can do just this. As a proof of concept, I made a [Sample Data](http://untra.github.io/polyglot/sample/) page that uses [strings stored in a .yml file](https://github.com/untra/polyglot/tree/site/_data), that are then applied to a universal [sample.md file](https://github.com/untra/polyglot/blob/site/sample.md). This is something that you can do with your multilingual site, and I recommend using this design pattern for small strings and rich content.

_I highly advise against doing this for every string in your website._

- You have to manage keys and values between multiple dictionaries. It becomes easy to make mistakes, especially if those strings are in languages you don't personally know.
- It does not fallback to your `default_lang` if you are missing content.
- Adding a new language to your website is no longer trivial when exclusively using this pattern.
- Debugging translation mistakes and typos, `"` and `'` marks, and so on becomes your life. It is not fun. It is a chore.

I hope this helps. Please head my warning. :smile:

**Comment by equinusocio** [comment]
Thanks man!
