### ISSUE TITLE
Jekyll 3.0.0 support?

### ISSUE THREAD

**Issue by needcaffeine** [untra/polyglot#2]
Hi— I'm using Jekyll 3.0.0 and I installed this plugin using a Gemfile and including it in my gems list in _config.yml. To build, I do a `bundle exec jekyll build`, which loads all my other plugins but I'm unable to get past ``require': cannot load such file -- jekyll-polyglot (LoadError)`.

I see that you don't promise compatibility higher than 2.5.3, but I just want to make sure I'm not doing something wrong and this plugin is in fact supposed to work in 3.0.0.

Thanks.

**Comment by untra** [comment]
Hi @needcaffeine ! Thanks for trying out Polyglot! :+1: 

I didn't promise support for jekyll 3.0, and currently I'm learning how to properly write jekyll plugins using the new [hooks](http://jekyllrb.com/docs/plugins/#hooks) plugin framework. I do intend to release a version specifically for Jekyll 3.0 compatibility within a few weeks. I've been a bit busy with a few other projects, but I am still actively working on polyglot.

That said, **I recommend all Jekyll 3.0 users just copy the [polyglot.rb](https://github.com/untra/polyglot/blob/master/lib/polyglot.rb) file into their `_plugins` folder instead of using the gem.** I will update the readme to reflect that. Polyglot should still work with Jekyll 3.0 that way.

The gem is just the polyglot.rb file, and a dependency to use a later version of the [https://github.com/guard/listen](https://github.com/guard/listen) then what Jekyll 2.5.3 uses. However Jekyll 3.0 uses the updated listen gem anyways, so there really is no reason to use the gem'd version of polyglot with Jekyll 3.0. (for specifics, see https://github.com/jekyll/jekyll-watch/issues/28)

So yeah, try just copying the polyglot.rb file, and let me know if that works for you.

**Comment by untra** [comment]
Polyglot v1.1 has been released! This fully supports jekyll 3.0 blogs. Just drop the [polyglot.rb](https://github.com/untra/polyglot/blob/master/lib/polyglot.rb) file into your `_plugins` folder, and you're ready to fly like an *eagle*!

Let me know if you have any further trouble.
Cheers,
untra

**Comment by needcaffeine** [comment]
Oh perfect. I'll give it a try when I get back to my desk from vacation!
