### ISSUE TITLE
Feature request: either work with an existing jekyll sitemap plugin or generate sitemap

### ISSUE THREAD

**Issue by scgupta** [untra/polyglot#29]
Currently I am using [jekyll-sitemap](https://github.com/jekyll/jekyll-sitemap) for generating sitemap, see [example](https://github.com/lutf-e-ghazal/lutf-e-ghazal.github.io/tree/site). And polyglot helps generating sitemap.xml for default and other languages in their respective lang dirs. But the links in all generated sitemap.xml files are for default languages. So either there is some setting that I don't understand something and doing wrong, or polyglot currently doesn't target generating sitemap.xml

Ideally, I wish there was sitemap as explained in [this google webmaster tip](https://support.google.com/webmasters/answer/2620865?hl=en) instead of multiple sitemap.xml (as it is not for visitor, but crawl bot). But even if there are separate sitemap.xml being generated, I wish somehow links were correct.

I see two possibilities to achieve it:
1. polyglot works with a common jekyll sitemap plugin
2. generates sitemap itself (I am not sure if feasible, but considering it probably knows about all pages being generated and cares about I18n_Headers etc., it might be something to think about).

Thanks @untra for such wonderful support and help that I got from you for the two issues I faced.
+satish

**Comment by aensidhe** [comment]
I would like to see correct sitemap.xml too.

**Comment by jerturowetz** [comment]
I'm pretty sure polyglot is running after jekyll-sitemaps, and is copying the `sitemaps.xml` file to the other language folder roots without any processing as if it was any other file.

As this has been a floating issue since 2016, I'm going to resolve it in my project by removing the sitemaps plugin & building a sitemap file using polyglot vars. I'll post my example once finished (maybe we could put in a guide or in the example documents).

If you've already created anything which could give me a head start feel free to share.

**Comment by MPJHorner** [comment]
Anything get resolved with this? @jerturowetz interested to see what you have created.

**Comment by jerturowetz** [comment]
Just wrapped it up now! I've ditched using a sitemap plugin and just built the sitemap manually.

There's a few items to note:

- For cleanliness, `sitemap.xml` is listed in the `exclude_from_localization` array in `_config.yml`
- I did not specify any `hreflang` attributes in the sitemap as my posts/pages have `hreflang` specified in their `<head>`. I do it manually, but polyglot includes `{{ I18n_Headers }}` which built the appropriate tags for you.
- You have to include some empty yaml at the top of sitemap in order to get jekyll to process the file

```
---
layout:
---

<!-- I am using hreflang attributes on a page by page basis in the <head> so no need to include it here -->
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
{% for lang in site.languages %}

    <!-- loops through all site collections INCLUDING posts -->
    {% for collection in site.collections %}
        {% for item in site[collection.label] %}
            <url>
                <loc>{% if lang == site.default_lang %}{{ item.url | absolute_url }}{% else %}{{ item.url | prepend: lang | prepend: '/' | absolute_url }}{% endif %}</loc>
            </url>
        {% endfor %}
    {% endfor %}

    <!-- It would probably be better to use the where_exp filter in the for loop, but I dont think different types of expressions are supported -->
    {% for node in site.pages %}
        {% unless site.exclude_from_localization contains node.path %}
            <!-- I am assuming if there's not layout assigned, then not include the page in the sitemap, you may want to change this -->
            {% if node.layout %}
                <url>
                    <loc>{% if lang == site.default_lang %}{{ node.url | absolute_url }}{% else %}{{ item.url | prepend: lang | prepend: '/' | absolute_url }}{% endif %}</loc>
                </url>
            {% endif %}
        {% endunless %}
    {% endfor %}

{% endfor %}
</urlset>

```

**Comment by MPJHorner** [comment]
@jerturowetz looks ideal. You should put this on the Readme.md

**Comment by hacketiwack** [comment]
@jerturowetz, the proposed method works great. However, as the plugin jekyll-sitemap is removed, no robots.txt is generated anymore.

**Comment by boamaod** [comment]
In my [custom sitemap](https://github.com/ausadvalimised/ausadvalimised.ee/blob/80bc2cf17f0c4a535eec8403994f95a91c82f411/sitemap.xml) similar to [the one above](https://github.com/untra/polyglot/issues/29#issuecomment-437914782) I am having hard time with excluding from the sitemap document nodes without translation, that is pages of the documents that are rendered as [untranslated fallback pages](https://github.com/untra/polyglot#fallback-language-support). It might be technically not wrong to have them listed, but since sitemap is used to index web sites, it is not really useful to index fallback pages without actual translation, since they would be just duplicates of the originals and the metadata stating the language would be incorrect. It's better not to index them at all and exclude them from sitemap, despite the fact that they show up on the web resulting from the fallback mechanism. This would be also the most coherent way to do it, if [sitemap indexes](https://github.com/jekyll/jekyll-sitemap/pull/300) referring to language specific sitemaps are used.

Currently only decent option to solve this is to [create placeholder pages](https://leo3418.github.io/collections/multilingual-jekyll-site/add-no-translation-msg.html) for documents without translation with the warning "this document is not translated yet, please refer to the original document". This is a viable option and with a special template one could include the original or default language page with a separate language tag in HTML, but it seems to overcomplicate the website presentation and not listing those dummy fallback pages would still make sense.

I think having a variable to list available translations suggested [here](https://github.com/untra/polyglot/issues/119) might be useful for solving these kinds of issues. Or is there another way to solve this? I think similar problems appear also when rendering menus and site archives, also in language switcher, where one might want to indicate if there is an actual translation available.

**Comment by untra** [comment]
https://github.com/untra/polyglot?tab=readme-ov-file#sitemap-generation
Thank you @jerturowetz for your solution! added to the readme
