### ISSUE TITLE
Files structure and naming conventions (configuration in general)

### ISSUE THREAD

**Issue by Vaggos** [untra/polyglot#3]
Hello @untra.
I am trying to use your plugin for my site, but I am having difficulty understanding how it really works. For example you write “It doesn't matter where you put the files or what you name them. What matters is that your English about page has lang: en in the front matter.” And then you are using an example about the “about” page. My question is: Must we have a separate file for each “about” page or  they are all declared in a single file? If they must be different files, what is the naming convention of the files? Eg, about-en.md, about-fr.md, about-de.md? Moreover, how can I set up the main navigation to show the links in the active language and point to the relevant content in the active language?
I am struggling to set this up. If you could help me I would really appreciate it.
Thank you for your time and your plugin, anyway.

**Comment by untra** [comment]
Hi @Vaggos !
> My question is: Must we have a separate file for each “about” page or they are all declared in a single file?
Okay! Something to know about Jekyll blogs is that every page/post/document on your blog *must* correspond with a unique file in your project. You cannot have multiple webpages corresponding to the same file. This is true of all jekyll blogs, not just the polyglot plugin.

Polyglot associates similar files by their permalinks. That is, if you have two pages like so:
*about-fr.md*
```md
title: Nous Contacter
permalink: /about
lang: fr
```
*about-en.md*
```md
title: Contact Us
permalink: /about
lang: en
```

Polyglot knows they correspond to the same route `/about`, and will associate the correct `fr` page with the french website, while associating the `en` page with the english website.

> For example you write “It doesn't matter where you put the files or what you name them. What matters is that your English about page has lang: en in the front matter.”

It just occurred to me this is no longer 100% true for posts. Jekyll 3 changed how posts are routed to, and their permalink *is* determined by their file name and location (if it's not explicitly added). I'm going to amend that with:
> “Files that correspond to similar routes should have identical permalinks. If you don't provide a permalink for posts, ___make sure you are consistent___ with how you place and name corresponding files: `_posts/2010-03-01-salad-recipes-en.md`, `_posts/2010-03-01-salad-recipes-sv.md` and `_posts/2010-03-01-salad-recipes-fr.md`. Organized names will generate consistent permalinks when the post is rendered, and polyglot will know which posts correspond to similar routes and their languages.”

In short:
* Be consistent with how you name and place your *posts* files
* Always give your *pages* permalinks in the frontmatter
* Don't overthink it, :wink: 

>Moreover, how can I set up the main navigation to show the links in the active language and point to the relevant content in the active language?

Multi-language navigation is trickier, as it must be generated from rich content rather than from an entire page. It's also very customized to how you want your site to look and behave. This is where you need to get creative with how you design your jekyll website, and how you write your liquid and html. I'll put up a tutorial on the wiki later that better describes how to make a generic multi-language navbar. For now, look at how I [generate the "Hello"](https://github.com/untra/polyglot/blob/site/_includes/sidebar.html#L5) speech bubble for the [polyglot homepage](http://untra.github.io/polyglot/). It requires coordinating `site.active_lang` with a dictionary in the [_config.yml](https://github.com/untra/polyglot/blob/site/_config.yml#L4). You'll need to do something similar when designing your navbar.

I'll add to the readme and wiki later to better address these concerns, and make it clearer for future users. For a good example of how to set this up, look at the [site](https://github.com/untra/polyglot/tree/site) branch, which is the file structure for the [polyglot homepage](http://untra.github.io/polyglot/).

I hope this inspires you!

**Comment by Vaggos** [comment]
Thank you @untra. That got a lot sorted out. I got my pages going. Now, I have to study the example you provided for the multilingual navbar. Can you understand if the way Sylvain Durand (https://www.sylvaindurand.org/making-jekyll-multilingual/) did it is similar to yours? I am asking both out of curiosity and a possibility to standardize something.
Thanx again, and please let me know if I can contribute in any way. I will be glad.

**Comment by needcaffeine** [comment]
I'm adding to this question about organization instead of starting my own thread. Apologies is that's not proper etiquette.

My site is in four different languages. In order to not gum up the base folder, I have all the files in their specific language folders. It looks like this:

```
├── en
│   ├── about.html
│   ├── index.html
│   └── services.html
└──es
    ├── about.html
    ├── index.html
    └── services.html
```

The relevant settings in _config.yml are:
```
# Polyglot
languages: ["en", "es"]
default_lang: "en"

defaults:
     scope:
       path: en
     values:
       layout: default
       lang: en
   -
     scope:
       path: es
     values:
       layout: default
       lang: es

permalink: pretty
```

What ends up happening is that my _site is generated looking like this. The en folder looks fine, but holy crap that es folder.
```
├── en
│   ├── about.html
│   ├── index.html
│   └── services.html
├── es
│   ├── about.html
│   ├── en
│   │   ├── about.html
│   │   ├── index.html
│   │   └── services.html
│   ├── es
│   │   ├── about.html
│   │   ├── index.html
│   │   └── services.html
│   ├── index.html
│   └── services.html
```
I've fiddled with different settings but I can't seem to fix it. Any ideas?

**Comment by needcaffeine** [comment]
Deleted my post. Figured it out.

**Comment by untra** [comment]
@Vaggos [I made a small introduction post](https://github.com/untra/polyglot/wiki/Managing-Supported-Languages) to the wiki explaining The general approach to using Polyglot (not specifically a navbar tho).

I'm going to close this issue. Let me know if you are still having any trouble, or if you need help working with Polyglot.

cheers,
untra

**Comment by Vaggos** [comment]
Thank you very much @untra. I have figured out most of it, but some extra instructions are always welcome. Thanx again!
