### ISSUE TITLE
Blog Title Only in One Language

### ISSUE THREAD

**Issue by bradonomics** [untra/polyglot#34]
In order to get the paginator to work I've created a directory called blog and added an index.html file inside that directory. That file gets duplicated for every language and pulls the posts for the appropriate language as it should, but there is only one title in the frontmatter for that index file.

I tried creating multiple index files with the index.[lang].html naming convention, but that didn't work. Aside from using a data.yml file, how can I have multiple titles and descriptions for the blog/index.html file?

**Comment by untra** [comment]
Hi @bradonomics 
You have to take advantage of your liquid tags. You can have in your `_config.yml`:
```yml
title:
  en: "my website"
  es: "Mi sitio web"
  ...
```
and then in your `_includes/head.html`:
```html
{% assign lang = site.active_lang %}
<head>
...
<title>{{site.title[lang]}}</title>
...
</head>
```
This is a technique you will need to use for all rich content and short strings throughout your website. You'll see I do [something similar](https://github.com/untra/polyglot/blob/site/_config.yml#L18) for [polyglot.untra.io/](http://polyglot.untra.io/)

I hope this helps!
@untra

**Comment by bradonomics** [comment]
I'm talking about the page title not the site title. I see how that's a little confusing after re-reading my post above

I have a static homepage, so the blog loop is in `blog/index.html`. That feeds into the `_layouts/default.html` file where the header is called. The `_includes/header.html` file has this: `<h1>{{ page.title }}</h1>`

Having only one `blog/index.html` file means only one set of frontmatter—only one title.

**Comment by untra** [comment]
If you only have one `blog/index.html` then you will only have one `{{ page.title }}` to use. That's just physics, y'know? The solution is to assign some frontmatter / liquid variable to a dictionary with keys matching your languages as I mentioned earlier. [Per the documentation](https://jekyllrb.com/docs/frontmatter/#custom-variables):
>  For instance, if you set a title, you can use that in your layout to set the page title:
```html
<!DOCTYPE HTML>
<html>
  <head>
    <title>{{ page.title }}</title>
  </head>
  <body>
    ...
```

`titles` aren't mandatory, they're entirely optional. How you use them defines their interface. You only have one `page.title` in your `blog/index.html` to operate on. Instead of assigning it as a string, assign it as a dictionary:
```yaml
title:
  en: "my website"
  es: "Mi sitio web"
  ...
```
And then use the same design pattern to display the page title:
```html
{% assign lang = site.active_lang %}
<body>
...
<h1>{{site.title[lang]}}</h1>
...
</body>
```

That's really the only solution; if you only provide one string, you'll only get one string.
I hope this helps (and that I'm understanding the question correctly 😬 )

**Comment by bradonomics** [comment]
I tried adding the title array in the frontmatter of `blog/index.html` before, but it was all wonky. The output was plain text. I bet my mistake was the `assign` tag. I didn't add that. I bet that would get the expected output.

Unfortunately I've had to bail on the polyglot plugin for other compatibility reasons so I don't have an active repo to test this. I do appreciate your help and if I use the plugin again, I'll post the confirmation here.
