### ISSUE TITLE
Make the i18n_headers Liquid tag more useful

### ISSUE THREAD

**Issue by svoop** [untra/polyglot#36]
Maybe I'm too blind to see, but it seems the `I18n_headers` Liquid tag cannot be used with variables and thus I have to hardcode the site URL – not very DRY since it's set in `_config.yml` already.

From the docs:

```
{% I18n_Headers https://untra.github.com/polyglot %}
```

The problem with the above is that you can't pass in variables such as:

```
# Won't work:
{% I18n_Headers site.url %}
```

Any chance to get this changed to something like:

```
{% i18n_headers "https://untra.github.com/polyglot" %}
{% i18n_headers site.url %}
```

(In order not to break existing installations, the improved tag is all lowercase. The mixedcase variant could be deprecated and eventually removed.)

What do you think?

**Comment by untra** [comment]
[Other people have commented on this before](https://github.com/untra/polyglot/issues/20). I prefer other suggestions of just reading in the `url` from the `site` config, and having no parameters passed in.

`{% i18n_headers %}`

That said, I'm waiting for other work on the main Jekyll project to get completed before I continue any more work with polyglot. [This PR](https://github.com/jekyll/jekyll/pull/5344) when completed will define how plugins like mine should be written, so that hopefully this plugin can be run on github pages.

Thanks for the input @svoop

**Comment by untra** [comment]
With #48 you should be able to use the `{% I18n_Headers %}` tag as is, and it will default to the `site.url`. You can see this in effect live on the [polyglot website](http://polyglot.untra.io/), with [the source code here](https://github.com/untra/polyglot/blob/master/site/_includes/head.html#L6).

Cheers!
