### ISSUE TITLE
Ability to translate URLs with domain name included

### ISSUE THREAD

**Issue by vlsi** [untra/polyglot#42]
URLs like `http://localhost:4000/page` do not get translated.
I wonder if polyglot could translate variations of links with `site.url` and `site.baseurl` included.

Here's the "offending" template: https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/masthead.html#L12-L14

PS. Even though I think links without domain name would be better, it seems that there is just lots of templates with domain name included.

**Comment by untra** [comment]
polyglot is only going to translate *relative* urls (`<a href="/about">`). It is designed not to attempt to translate absolute urls like `http://localhost:4000/page`. This is because absolute urls cannot be guaranteed to resolve to a site with a page whose layout matches polyglots `/i18n/page` structure.

Basically, after jekyll renders the html for the page it then does a regex match for all relative urls. If the rendered page has a link that says `<a href="http...` it will not match that, and intentionally skip it.

**Comment by vlsi** [comment]
>This is because absolute urls cannot be guaranteed to resolve to a site with a page whose URI matches the expected /i18n/page structure.

Well, how jekyll's `absolute_url` differs from the relative urls polyglot parses with regexp?
I think it is rather safe to translate those kind of links as well.
I do understand that polyglot uses regex match over final page. However I do not get why do you intentionally skip absolute URLs that point to the *current* blog. Any reason?

I'm using https://github.com/mmistakes/minimal-mistakes theme. That theme prints absolute urls everywhere. Frankly speaking I've no idea why it sticks with absolute urls, but I don't find strong justification why should it use relative URLs.

**Comment by untra** [comment]
You can edit the minimal mistakes theme so it doesn't use absolute urls, which can solve the problem. You will have to change the liquid tags in a lot of files, but that's not a tough edit.
_Difficulty_: 2/10 trivially easy, some repetitive work.

Or you can edit the regex yourself to match `https` and `http` localhost urls, and submit a PR. [Here's the dynamically generated regex in question](https://github.com/untra/polyglot/blob/master/lib/jekyll/polyglot/patches/jekyll/site.rb#L110). Just make sure your changes keep tests passing. You'll probably have to [update the tests too](https://github.com/untra/polyglot/blob/master/spec/tests/lib/jekyll/polyglot/patches/jekyll/site_spec.rb#L54), because that regex is a critical component of Polyglot's functionality.
_Difficulty_: 9/10 pretty tough, very little payoff.

Designing a regex that efficiently and correctly matches patterns correctly is hard. Designing a dynamic regex that can take in multiple parameters to accomodate multiple edgecases is harder. The change in the regex to accept relative urls, but not absolute urls, *except* localhost urls, is just plain inefficient. 👎
