### ISSUE TITLE
Linking to another language-version of a page

### ISSUE THREAD

**Issue by MadsMadsDk** [untra/polyglot#51]
Hello @untra!

Thank you for writing a cool plugin for jekyll, it's very useful. I have a question regarding linking to another language-version of a page.

I tried following your example of creating language-links in the sidebar, but with slight modifications as I only have two languages for now.

**The case**

I have two languages. English (default) and danish. In my navigation file, which is included using `{% include %}`, I have the following link:

__includes/en/nav.html_

```html
  <li class="nav__item">
    <a class="nav__link" href="{% if site.active_lang == 'en' %}/da{% endif %}{{ page.url }}">
      <img src="/assets/flags/dk.png" height="24" alt="da" width="24">
    </a>
  </li>
```

__includes/da/nav.html_

```html
  <li class="nav__item">
    <a class="nav__link" href="{{ site.baseurl }}{{ page.url }}">
      <img src="/assets/flags/uk.png" height="24" alt="en" width="24">
    </a>
  </li>
```

This results in the following output for the page "cookie-policy" for example:

__site/cookie-policy/index.html_

```html
  <li class="nav__item">
    <a class="nav__link" href="http://localhost:4000/da/cookie-policy/">
      <img src="/assets/flags/dk.png" height="24" alt="da" width="24">
    </a>
  </li>
```

__site/da/cookie-policy/index.html_

```html
  <li class="nav__item">
    <a class="nav__link" href="/da/cookie-policy/">
      <img src="/assets/flags/uk.png" height="24" alt="en" width="24">
    </a>
  </li>
```

The front-matter for these pages correctly includes "lang: da" and "lang: en", and also have equal permalinks. My _config.yml includes 'baseurl: ""'.

So my question is, what do I need to change in __includes/da/nav.html_ to correctly link to the english equivalent of the current page?

**Comment by untra** [comment]
Hi @MadsMadsDk!

Check out [how I do the language navigation](https://github.com/untra/polyglot/blob/master/site/_includes/sidebar.html#L40) in the example polyglot website:
```html
  {% for tongue in site.languages %}
<a {% if tongue == site.active_lang %}style="font-weight: bold;"{% endif %} href="{% if tongue == site.default_lang %} {{site.baseurl}}{{page.url}} {% else %} {{site.baseurl}}/{{ tongue }}{{page.url}} {% endif %}">{{ tongue }}</a> |
  {% endfor %}
```

Ideally you shouldn't have two different `nav.html files`, you should have just one and make it work for both of your languages. That would be my first suggestion.

Your `_site/da/cookie-policy/index.html` page has the url showing up as `href="/da/cookie-policy/"`. This is because the url is relative, and so the regex parser thinks it should correct the url to keep you on the `da` site.

I would also recommend adding a space after `href="` in both your navigations. This prevents the regex from matching the relative url, while keeping the linking correct.

_includes/da/nav.html
```html
 <li class="nav__item">
    <a class="nav__link" href=" {{ site.baseurl }}{{ page.url }}">
      <img src="/assets/flags/uk.png" height="24" alt="en" width="24">
    </a>
  </li>
```

Does that do it?
-@untra

**Comment by MadsMadsDk** [comment]
Thanks for your swift response!

I can see how it would make sense to only have one `nav.html` file, and then translate the link strings. I'll work on that once I need to support more languages.

For now, it works perfectly with two files and adding a space after `href="`!

Thanks a lot for you help,
Mads
