### ISSUE TITLE
Solution for images localization?

### ISSUE THREAD

**Issue by willsu** [untra/polyglot#61]
First of all, thank you for the very helpful Gem.

I have a documentation project that requires the images to be localized as well as the `*.md` documents. 

My desired pattern would be the following files would be processed the same way that the markdown documents:
```
img/launch_instance_details.png <-- English version
img/launch_instance_details.fr.png <-- French version
```

My desired result (`dist` is my build directory):
```
dist/fr/img/launch_instance_details.png <-- the English Version
dist/fr/img/launch_instance_details.png <-- this should be the French version (img/launch_instance_details.fr.png)
```

My actual result:
```
dist/fr/img/launch_instance_details.png <-- the English Version
dist/fr/img/launch_instance_details.fr.png
dist/fr/img/launch_instance_details.png
```

Is image and/or static asset localization currently supported with by your library or known workarounds that could be used to accomplish this task? I can provide further details as necessary.

One technique I tried that has not panned out for me:

I moved my `img` directory to `_img` and configured `img` as a collection in the `_config.yml` like so:

```
  img:
    output: true
    permalink: /img/:path/
```

The images all get built into the respective language directories, but the language specific images `*.fr.png` do not get replaced as they do in the markdown documents. Thus, the result is effectively the same as the first scenario I described above. I imagine that the issue is due to the missing `lang: fr` 'Front Matter' in the images.. I tried adding Front Matter to one of the images, but I (unsurprisingly) get 'invalid byte sequence' errors during the Jekyll build process.

Any help would be greatly appreciated. Many Thanks!

**Comment by untra** [comment]
Polyglot is not designed to localize media or other assets. This is not part of it's functionality, and probably will not be added in.

However I think you can achieve this same functionality with some crafty liquid tags. When displaying your image, you can embed the liquid variables into the tag name like so:
```md
![My helpful screenshot]({{ site.url }}/img/launch_instance_details.{{active_lang}}.png)
```
assuming you mark your english `default_lang` images with an `.en.png` suffix, that should do the trick.

I recommend including your images and media assets in the `exclude_from_localization` section of your `_config.yaml`. Otherwise it will likely make a copy of your `img` diorectory for each version of your site. That can get very heavy and expensive, real quick.

Good luck!
