### ISSUE TITLE
Improving Polyglot / More info about the plugin

### ISSUE THREAD

**Issue by Anthony-Gaudino** [untra/polyglot#7]
@untra, I would like to create a Jekyll 3 website for an open source project and I'm currently looking for a i18n plugin to help me during the website development. I tried the [jekyll-multiple-languages-plugin](https://github.com/screeninteraction/jekyll-multiple-languages-plugin) and I just created a [pull request](https://github.com/screeninteraction/jekyll-multiple-languages-plugin/pull/55) for it with some changes and fixes that maybe could be useful for Polyglot too.

--------

Polyglot seems to be easier to use, and I am considering on using it.

I would like to know if there are any known issues with the plugin.

Also I would like to know why you didn't provided a gem for the version compatible with Jekyll 3. In my opinion it's so much easier to use `Bundler`, add the plugin to the `Gemfile` and then just add this to the Jekyll `_config.yml`:

```ruby
gems: 
  - jekyll-polyglot
```
to load the plugin into Jekyll.

**Comment by untra** [comment]
Hi @Anthony-Gaudino !

>I would like to know if there are any known issues with the plugin.

Are there any known problems with the plugin? Not really (or that I know of), however there definitely isn't enough well-written documentation on how to use Polyglot. I need to write more documentation, and put a few examples up. I'm a student in finals mode right now, and polyglot isn't my fulltime job. I do want to put up a decent tutorial on making a seriously badass multilanguage navbar, or a javascript plugin to redirect users depending on their browsers language. That said, I'm here to answer any questions about the plugin, and help out users however I can.

I want to emphasize that Polyglot is lightweight, and provides only a bare-minimum set of features. I would say Polyglot is for more advanced Jekyll users / web developers who mean business. While it can be implemented on any size jekyll blog, it's two biggest and baddest features are the [automatic url relativization](https://github.com/untra/polyglot#relativized-local-urls) and the [parallelized site building](https://github.com/untra/polyglot#how-it-works). These are features [Industrial or commercial scale websites](https://logrhythm.com) need so they can focus on content aggregation and fast build times over sanitized sitemaps and minute-long build times.

>Also I would like to know why you didn't provided a gem for the version compatible with Jekyll 3. In my opinion it's so much easier to use `Bundler`, add the plugin to the `Gemfile` and then just add this to the Jekyll `_config.yml`:

> ```ruby
gems: 
  - jekyll-polyglot
```
>to load the plugin into Jekyll.

I can write a blogpost about this :laughing: 

There are different ruby camps that say when a gem is necessary. Polyglot is less than 200 lines of ruby. It fits perfectly as a `_plugin/` folder dropin, and as of Jekyll 3, it has no dependencies outside of Jekyll's scope. IMHO, making it into a gem is overkill, and it means users have to manage a new gem dependency for their project. A serious project will want to be slim on gem dependencies.

Another camp says that the size of the gem doesn't matter, and because it would have no complex dependencies outside of Jekyll, then Polyglot as a gem wouldn't be a headache to seriously manage. They also say it means I can push updates and other polyglot version upgrades to current users. That's cool too.

I'm here to help though. If you seriously want it available as a gem, I can make it a gem. I think it's overkill, but I can get it done. Just give me a few days through finals though, yeah? :memo: 

Cheers,
untra

**Comment by Anthony-Gaudino** [comment]
Thank you for the answers @untra.

I'm really in doubt on what i18n plugin to use, there are many language plugins. Not taking into account the old ones that don't have recent activity, I still have these to choose:

* [jekyll-multiple-languages](https://github.com/liaohuqiu/jekyll-multiple-languages) (Might not work with Jekyll 3)
* [jekyll-language-plugin](https://github.com/vwochnik/jekyll-language-plugin)
* [polyglot](https://github.com/untra/polyglot)
* [jekyll-multiple-languages-plugin](https://github.com/screeninteraction/jekyll-multiple-languages-plugin)

You may want to check those other projects for improvements on Polyglot, or maybe to merge the plugins into a single `ultra plugin` :smile:

About the gem, I prefer using gems as much as possible, but the choice is yours to release Polyglot as a gem.

**Comment by untra** [comment]
@Anthony-Gaudino,

Thanks for your patience. I've been busy the past week with finals. I made polyglot a gem again. You should be able to install it by putting
```
gem 'jekyll-polyglot', '~> 1.1.1'
```
into your gemfile.

Of the plugins you listed, the [jekyll-multiple-languages-plugin](https://github.com/screeninteraction/jekyll-multiple-languages-plugin) you mentioned is [what I based](https://github.com/untra/polyglot#why) polyglot's implementation off of. You'll notice our configurations are similar.

But our executions are totally different. With their plugin you can do this:
```html
{% if site.lang == "sv" %}
    {% capture link1 %}{{ site.baseurl_root }}en{{ page.url}}{% endcapture %}
    <a href="{{ link1 }}" >{% t global.english %}</a>
  {% else if site.lang == "en" %}
    {% capture link2 %}{{ site.baseurl_root }}{{ page.url  }}{% endcapture %}
    <a href="{{ link2 }}" >{% t global.swedish %}</a>
  {% endif %}
```

With polyglot, you can do [this](https://github.com/untra/polyglot#relativized-local-urls) instead:
```html
<a href="{{ page.url  }}" >
```

If you decide to go with a different i18n jekyll plugin, I won't be sad. But I put a lot of effort into Polyglot so developers wouldn't have to tolerate egregious code bombs like that. :anguished: 

Let me know if you have any questions!
Cheers,
untra
