### ISSUE TITLE
Falling back to a non-default language

### ISSUE THREAD

**Issue by sxmichaels** [untra/polyglot#77]
I have a bit of an unusual situation to deal with regarding fallback languages. As far as I know, this is not possible in vanilla Polyglot, but I wonder if there are any workarounds that would allow me to implement this. My use case is as follows:

My website supports three languages: English, Simplified Chinese, and Traditional Chinese. The latter two are actually the same language, just written in different character sets with slight vocabulary differences. Generally, native speakers can read both, but are often more comfortable reading one. As such, I'd like my website to default to English, but in the case where e.g. a post only has Simplified Chinese and English versions, attempting to access the Traditional Chinese version should fall back to Simplified Chinese, not English. The opposite should also be the case (Simplified not available redirects to Traditional if available).

Is such a thing possible with Polyglot? I'm willing to make any modifications myself, but I'm very new to Ruby and don't quite know where to start. One solution I thought of is to allow each language to specify its own fallback language — there could be a better way, though.

**Comment by untra** [comment]
Hi @sxmichaels 👋 
Ummm... This is definitely a trickier situation. Polyglot is built around the assumption that there is only one default language to fallback to. The pattern you're describing is currently not available with the current version of polyglot.

I'm currently working on a 2.0 branch of polyglot. I'll keep your use-case in mind for that release.
Cheers,
untra

**Comment by pserwylo** [comment]
> I have a bit of an unusual situation to deal with regarding fallback languages.

This is not such an unusual situation. Most translation systems will use `language-REGION` codes. 

Given the following:
 * `fr_FR`
 * `fr_CA`
 * `fr`
 * `en_US`
 * `en`

You'd probably expect a user asking for `fr_FR` to fall back to `fr` when not available, and to `en` when `fr` is unavailable. It gets a bit trickier when you say the following is avaialble:

 * `fr_FR`
 * `fr_CA`
 * `en`

(which is probably more similar to your Chinese example). If `fr_FR` is unavailable, it may be more desirable to select `fr_CA` instead of `en` as a fallback language.

If it helps, here is how we've implemented this in our Jekyll project (the broader website depends on polyglot, but this part is unique to us so is done in a separate plugin):

 * [Source](https://gitlab.com/fdroid/jekyll-fdroid/blob/master/lib/fdroid/App.rb#L190)
 * [Tests](https://gitlab.com/fdroid/jekyll-fdroid/blob/master/spec/lib/fdroid/FDroidIndex_spec.rb#L16)

**Comment by vlsi** [comment]
>but this part is unique to us so is done in a separate plugin):
>Source
>Tests

^^^ be careful. The sources above are AGPL-licensed.

**Comment by pserwylo** [comment]
@vlsi - Thanks, I appreciate the caution. Our [plugin](https://gitlab.com/fdroid/jekyll-fdroid/blob/master/LICENSE) (and indeed the [website](https://gitlab.com/fdroid/fdroid-website/blob/master/LICENSE) we are building using Jekyll) is also AGPL licensed, so all is well on our end.

**Comment by vlsi** [comment]
My main idea was AGPL is not compatible with plolyglot's license, so care should be taken for not watching into AGPL code before implementing similar for polyglot )

**Comment by sxmichaels** [comment]
Thanks for the quick responses, everyone. I suspected it wasn't possible in current polyglot but I'm glad support might be forthcoming. Later on I might try to implement something like pserwylo's solution in a polyglot fork; if I'm confident enough in my code I'll put up a PR for it.

I'll close this issue for now.
