### ISSUE TITLE
Incompatible with jekyll-livereload?

### ISSUE THREAD

**Issue by derpoho** [untra/polyglot#80]
Hello,

since installing the polyglot bundle (nice work btw) livereload stopped working.
I used jekyll-livereload (https://github.com/RobertDeRose/jekyll-livereload).

Is this a known issue? I couldn't find anything.

I am new to Jekyll and it's process, but i guess it has something to do with the patching: https://github.com/RobertDeRose/jekyll-livereload/blob/master/lib/jekyll-livereload/serve.rb#L17

**Comment by untra** [comment]
I have not tested polyglot with jekyll livereload, but from the way it operates I am not surprised you are having problems. Polyglot also does it's own "monkey-patching" to get things done before the serve command.

You can try setting `parallel_localization: false` in the `_config.yml`. That may fix the bad behaviour, but in all likelihood the problem comes from those modifications to `Site.process`. From the [polyglot readme](https://github.com/untra/polyglot#how-it-works):

> `Jekyll::Site.process` is the entry point for the Jekyll build process. Take care whatever other plugins you use do not also attempt to overwrite this method. You may have problems.

**Comment by derpoho** [comment]
@untra Thanks for the suggestion, setting the `parallel_localization` to `false` solves this. But i wonder if there are any sideeffects. Can't see anything currently.
