### ISSUE TITLE
Error when switch to other languages

### ISSUE THREAD

**Issue by totoroyyb** [untra/polyglot#92]
Hi,

I tried to add two languages into my website by utilizing polyglot but I encountered some problems.
When I switch to second language by using language switcher, it failed to load font. Here is error message.
![image](https://user-images.githubusercontent.com/30278896/44985548-4cf60b00-afb3-11e8-864c-1c0a6dceb258.png)
It seems that polyglot automatically change the original path to one that included language prefix.

Is there any way to make polyglot escape these links and fetch font correctly?

Thanks for making such awesome plugin!

**Comment by untra** [comment]
Heya @totoroyyb 👋 ,

looking [here](https://github.com/totoroyyb/totoroyyb.github.io/blob/master/_config.yml#L5), you have 
> `exclude_from_localizations: ["javascript", "images", "css"]`

First off, that should be named `exclude_from_localization`: drop the `s`. That config option means that all content from those subfolders will not get relativised, which you want. Except you have your [javascript folder named js](https://github.com/totoroyyb/totoroyyb.github.io/tree/master/js) , so that content will all get localized, which you clearly don't want.

But that's not the problem, because you're not fetching that javascript anyways. You are getting your content from a cdn, and fetching it with [this weird liquid pattern](https://github.com/totoroyyb/totoroyyb.github.io/blob/master/_includes/head.html#L19-L53) that seems needlessly complex.

This approach to fetch your fonts for a particular page seems convoluted; I don't know if this is from a jekyll template or theme or something, but I'm not sure this is the best approach.

My suggestion: just put direct links to your cdn'd fonts and bootstrap.js/.css in your `head.html` file, and get rid of the complex routing logic that's currently there. Then make your `exclude_from_localization` config match the correct folder structure you have.

**Comment by totoroyyb** [comment]
@untra Thanks for your quick answer, I'll tried to simplify that!

**Comment by totoroyyb** [comment]
@untra I've managed that out! Thanks for your help!

**Comment by totoroyyb** [comment]
@untra I'm wondering is that possible to make website use the default language of user's browser? Cuz every time I navigate to my website, it always go to the default language of my website not user's browser. Thanks!

**Comment by untra** [comment]
you will need some javascript to check the browser language on first visit, and redirect to the appropriate page. [Relevent stackoverflow](https://stackoverflow.com/questions/24519370/javascript-redirection-according-to-browser-language). Good luck!
